### ISSUE TITLE
Error when passing associative array to merge function 

### ISSUE THREAD

**Issue by thaisonle** [gotenberg/gotenberg-php#6]
I'm getting an error when trying to pass an associative array to the merge call.

There are actually two errors I'm getting, the first happens when trying to pass it like normal with argument unpacking:

```
   $streams = array_map(
        fn($long_url) => Stream::path($long_url),
        $keyed_array_of_urls
    );

    $request = Gotenberg::pdfEngines($apiUrl)
        ->outputFilename('requested-name')
        ->merge(
            ...$streams
        );
```

The error I get is: `Too few arguments to function Gotenberg\Modules\PdfEngines::merge(), 0 passed`

So to remedy that and match the function signature, I use `array_shift()` to match:

```
    $request = Gotenberg::pdfEngines($apiUrl)
        ->outputFilename('requested-name')
        ->merge(
            array_shift$streams),
            array_shift$streams),
            ...$streams
        );
```

This gives me the error message: `Unsupported operand types: string + int` from `vendor/gotenberg/gotenberg-php/src/Modules/PdfEngines.php:41`

I'm currently getting around this by simply using `array_values()` and not passing an associative array.

```
    $request = Gotenberg::pdfEngines($apiUrl)
        ->outputFilename('requested-name')
        ->merge(
            ...array_values($streams)
        );
```

Just thought it might be worth bringing to your attention. Thanks for all the hard work!

**Comment by gulien** [comment]
Hello @thaisonle 👋

Actually, if you take a look at the `merge` signature: https://github.com/gotenberg/gotenberg-php/blob/d6236ecdd78d23c63f4623977df4a494adc5b945/src/Modules/PdfEngines.php#L34

There are 3 arguments: the first PDF, the second PDF and then the remaining PDFs. That’s explaining the first error AFAIK 😄 I did that to ensure there are at least two PDFs to merge.

For the second error, it’s because I’ve assumed the index of the array is an `int`, while in you case it’s a string 🧐 The fix is easy though, I’ll work on it.

Thanks for the heads up!

**Comment by thaisonle** [comment]
I understood your intent in the merge arguments but my `$streams` variable in the first call has at least 3 streams in it so it should unpack into those 3 parameters just fine. I'm not sure why it gives a weird error as if it's empty. That's why it's weird that using `array_shift()`, to pop off the same array elements, seems to bypass this error.

**Comment by gulien** [comment]
I guess it’s because only the third argument is explicitly variadic? Not sure though, it’s been the first I’ve played with variadic parameters in PHP.

**Comment by gulien** [comment]
@thaisonle version `0.1.4` should fix your issue :) thanks again for the heads up!
